"""Command ID to JSON Schema mapping."""

from __future__ import annotations

from typing import Any, Literal

from bq_inspector.schemas.input_schema import (
    CATALOG_ASPECT_TYPES_GET_INPUT_SCHEMA,
    CATALOG_ASPECT_TYPES_LIST_INPUT_SCHEMA,
    CATALOG_ENTRIES_GET_INPUT_SCHEMA,
    CATALOG_ENTRIES_LIST_INPUT_SCHEMA,
    CATALOG_ENTRIES_LOOKUP_INPUT_SCHEMA,
    CATALOG_ENTRY_GROUPS_GET_INPUT_SCHEMA,
    CATALOG_ENTRY_GROUPS_LIST_INPUT_SCHEMA,
    CATALOG_ENTRY_LINKS_GET_INPUT_SCHEMA,
    CATALOG_ENTRY_TYPES_GET_INPUT_SCHEMA,
    CATALOG_ENTRY_TYPES_LIST_INPUT_SCHEMA,
    CATALOG_GLOSSARIES_GET_INPUT_SCHEMA,
    CATALOG_GLOSSARIES_LIST_INPUT_SCHEMA,
    CATALOG_GLOSSARY_CATEGORIES_GET_INPUT_SCHEMA,
    CATALOG_GLOSSARY_CATEGORIES_LIST_INPUT_SCHEMA,
    CATALOG_GLOSSARY_TERMS_GET_INPUT_SCHEMA,
    CATALOG_GLOSSARY_TERMS_LIST_INPUT_SCHEMA,
    CATALOG_SEARCH_INPUT_SCHEMA,
    DATASETS_GET_INPUT_SCHEMA,
    JOBS_GET_INPUT_SCHEMA,
    JOBS_IMPACT_INPUT_SCHEMA,
    JOBS_LINEAGE_INPUT_SCHEMA,
    JOBS_LIST_INPUT_SCHEMA,
    JOBS_PERFORMANCE_INPUT_SCHEMA,
    JOBS_QUERY_INPUT_SCHEMA,
    JOBS_SUMMARY_INPUT_SCHEMA,
    LINEAGE_GRAPH_INPUT_SCHEMA,
    LINEAGE_LINKS_INPUT_SCHEMA,
    TABLES_GET_INPUT_SCHEMA,
    TABLES_LIST_INPUT_SCHEMA,
)
from bq_inspector.schemas.output_schema import (
    CATALOG_ASPECT_TYPES_GET_OUTPUT_SCHEMA,
    CATALOG_ASPECT_TYPES_LIST_OUTPUT_SCHEMA,
    CATALOG_ENTRIES_GET_OUTPUT_SCHEMA,
    CATALOG_ENTRIES_LIST_OUTPUT_SCHEMA,
    CATALOG_ENTRIES_LOOKUP_OUTPUT_SCHEMA,
    CATALOG_ENTRY_GROUPS_GET_OUTPUT_SCHEMA,
    CATALOG_ENTRY_GROUPS_LIST_OUTPUT_SCHEMA,
    CATALOG_ENTRY_LINKS_GET_OUTPUT_SCHEMA,
    CATALOG_ENTRY_TYPES_GET_OUTPUT_SCHEMA,
    CATALOG_ENTRY_TYPES_LIST_OUTPUT_SCHEMA,
    CATALOG_GLOSSARIES_GET_OUTPUT_SCHEMA,
    CATALOG_GLOSSARIES_LIST_OUTPUT_SCHEMA,
    CATALOG_GLOSSARY_CATEGORIES_GET_OUTPUT_SCHEMA,
    CATALOG_GLOSSARY_CATEGORIES_LIST_OUTPUT_SCHEMA,
    CATALOG_GLOSSARY_TERMS_GET_OUTPUT_SCHEMA,
    CATALOG_GLOSSARY_TERMS_LIST_OUTPUT_SCHEMA,
    CATALOG_RESOURCE_OUTPUT_SCHEMA,
    CATALOG_SEARCH_OUTPUT_SCHEMA,
    JOBS_GET_OUTPUT_SCHEMA,
    JOBS_IMPACT_OUTPUT_SCHEMA,
    JOBS_LINEAGE_OUTPUT_SCHEMA,
    JOBS_LIST_OUTPUT_SCHEMA,
    JOBS_PERFORMANCE_OUTPUT_SCHEMA,
    JOBS_QUERY_OUTPUT_SCHEMA,
    JOBS_SUMMARY_OUTPUT_SCHEMA,
    LINEAGE_GRAPH_OUTPUT_SCHEMA,
    LINEAGE_LINKS_OUTPUT_SCHEMA,
    TABLES_LIST_OUTPUT_SCHEMA,
)

CommandId = Literal[
    "catalog aspect-types get",
    "catalog aspect-types list",
    "catalog entries get",
    "catalog entries list",
    "catalog entries lookup",
    "catalog entry-groups get",
    "catalog entry-groups list",
    "catalog entry-links get",
    "catalog entry-types get",
    "catalog entry-types list",
    "catalog glossaries get",
    "catalog glossaries list",
    "catalog glossary-categories get",
    "catalog glossary-categories list",
    "catalog glossary-terms get",
    "catalog glossary-terms list",
    "catalog search",
    "datasets get",
    "jobs get",
    "jobs impact",
    "jobs lineage",
    "jobs list",
    "jobs performance",
    "jobs query",
    "jobs summary",
    "lineage graph",
    "lineage links",
    "tables get",
    "tables list",
]

JobsViewCommandId = Literal[
    "jobs get",
    "jobs impact",
    "jobs lineage",
    "jobs performance",
    "jobs query",
    "jobs summary",
]

SchemaKind = Literal["input", "output"]

_COMMAND_SCHEMAS: dict[str, Any] = {
    "jobs get:input": JOBS_GET_INPUT_SCHEMA,
    "jobs get:output": JOBS_GET_OUTPUT_SCHEMA,
    "jobs summary:input": JOBS_SUMMARY_INPUT_SCHEMA,
    "jobs summary:output": JOBS_SUMMARY_OUTPUT_SCHEMA,
    "jobs query:input": JOBS_QUERY_INPUT_SCHEMA,
    "jobs query:output": JOBS_QUERY_OUTPUT_SCHEMA,
    "jobs performance:input": JOBS_PERFORMANCE_INPUT_SCHEMA,
    "jobs performance:output": JOBS_PERFORMANCE_OUTPUT_SCHEMA,
    "jobs lineage:input": JOBS_LINEAGE_INPUT_SCHEMA,
    "jobs lineage:output": JOBS_LINEAGE_OUTPUT_SCHEMA,
    "jobs impact:input": JOBS_IMPACT_INPUT_SCHEMA,
    "jobs impact:output": JOBS_IMPACT_OUTPUT_SCHEMA,
    "jobs list:input": JOBS_LIST_INPUT_SCHEMA,
    "jobs list:output": JOBS_LIST_OUTPUT_SCHEMA,
    "datasets get:input": DATASETS_GET_INPUT_SCHEMA,
    "datasets get:output": CATALOG_RESOURCE_OUTPUT_SCHEMA,
    "tables list:input": TABLES_LIST_INPUT_SCHEMA,
    "tables list:output": TABLES_LIST_OUTPUT_SCHEMA,
    "tables get:input": TABLES_GET_INPUT_SCHEMA,
    "tables get:output": CATALOG_RESOURCE_OUTPUT_SCHEMA,
    "lineage links:input": LINEAGE_LINKS_INPUT_SCHEMA,
    "lineage links:output": LINEAGE_LINKS_OUTPUT_SCHEMA,
    "lineage graph:input": LINEAGE_GRAPH_INPUT_SCHEMA,
    "lineage graph:output": LINEAGE_GRAPH_OUTPUT_SCHEMA,
    "catalog search:input": CATALOG_SEARCH_INPUT_SCHEMA,
    "catalog search:output": CATALOG_SEARCH_OUTPUT_SCHEMA,
    "catalog entries lookup:input": CATALOG_ENTRIES_LOOKUP_INPUT_SCHEMA,
    "catalog entries lookup:output": CATALOG_ENTRIES_LOOKUP_OUTPUT_SCHEMA,
    "catalog entries get:input": CATALOG_ENTRIES_GET_INPUT_SCHEMA,
    "catalog entries get:output": CATALOG_ENTRIES_GET_OUTPUT_SCHEMA,
    "catalog entries list:input": CATALOG_ENTRIES_LIST_INPUT_SCHEMA,
    "catalog entries list:output": CATALOG_ENTRIES_LIST_OUTPUT_SCHEMA,
    "catalog entry-groups get:input": CATALOG_ENTRY_GROUPS_GET_INPUT_SCHEMA,
    "catalog entry-groups get:output": CATALOG_ENTRY_GROUPS_GET_OUTPUT_SCHEMA,
    "catalog entry-groups list:input": CATALOG_ENTRY_GROUPS_LIST_INPUT_SCHEMA,
    "catalog entry-groups list:output": CATALOG_ENTRY_GROUPS_LIST_OUTPUT_SCHEMA,
    "catalog entry-types get:input": CATALOG_ENTRY_TYPES_GET_INPUT_SCHEMA,
    "catalog entry-types get:output": CATALOG_ENTRY_TYPES_GET_OUTPUT_SCHEMA,
    "catalog entry-types list:input": CATALOG_ENTRY_TYPES_LIST_INPUT_SCHEMA,
    "catalog entry-types list:output": CATALOG_ENTRY_TYPES_LIST_OUTPUT_SCHEMA,
    "catalog aspect-types get:input": CATALOG_ASPECT_TYPES_GET_INPUT_SCHEMA,
    "catalog aspect-types get:output": CATALOG_ASPECT_TYPES_GET_OUTPUT_SCHEMA,
    "catalog aspect-types list:input": CATALOG_ASPECT_TYPES_LIST_INPUT_SCHEMA,
    "catalog aspect-types list:output": CATALOG_ASPECT_TYPES_LIST_OUTPUT_SCHEMA,
    "catalog entry-links get:input": CATALOG_ENTRY_LINKS_GET_INPUT_SCHEMA,
    "catalog entry-links get:output": CATALOG_ENTRY_LINKS_GET_OUTPUT_SCHEMA,
    "catalog glossaries get:input": CATALOG_GLOSSARIES_GET_INPUT_SCHEMA,
    "catalog glossaries get:output": CATALOG_GLOSSARIES_GET_OUTPUT_SCHEMA,
    "catalog glossaries list:input": CATALOG_GLOSSARIES_LIST_INPUT_SCHEMA,
    "catalog glossaries list:output": CATALOG_GLOSSARIES_LIST_OUTPUT_SCHEMA,
    "catalog glossary-categories get:input": CATALOG_GLOSSARY_CATEGORIES_GET_INPUT_SCHEMA,
    "catalog glossary-categories get:output": CATALOG_GLOSSARY_CATEGORIES_GET_OUTPUT_SCHEMA,
    "catalog glossary-categories list:input": CATALOG_GLOSSARY_CATEGORIES_LIST_INPUT_SCHEMA,
    "catalog glossary-categories list:output": CATALOG_GLOSSARY_CATEGORIES_LIST_OUTPUT_SCHEMA,
    "catalog glossary-terms get:input": CATALOG_GLOSSARY_TERMS_GET_INPUT_SCHEMA,
    "catalog glossary-terms get:output": CATALOG_GLOSSARY_TERMS_GET_OUTPUT_SCHEMA,
    "catalog glossary-terms list:input": CATALOG_GLOSSARY_TERMS_LIST_INPUT_SCHEMA,
    "catalog glossary-terms list:output": CATALOG_GLOSSARY_TERMS_LIST_OUTPUT_SCHEMA,
}


def get_command_schema(command: CommandId, kind: SchemaKind) -> Any:
    """Return the input or output JSON Schema for a command."""
    key = f"{command}:{kind}"
    schema = _COMMAND_SCHEMAS.get(key)
    if schema is None:
        raise ValueError(f"Unhandled schema key: {key}")
    return schema
